name: Docker Image Build

on:
  workflow_run:
    workflows: ["Test & Coverage"]
    types:
      - completed

jobs:
  docker:
    name: Build & Push to GHCR
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set image tags
        id: tags
        run: |
          SHA_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          echo "sha_tag=$SHA_TAG" >> $GITHUB_OUTPUT
          echo "branch_tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Build & Push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest \
                       -t ghcr.io/${{ github.repository }}:${{ steps.tags.outputs.branch_tag }} \
                       -t ghcr.io/${{ github.repository }}:${{ steps.tags.outputs.sha_tag }} .

          docker push ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:${{ steps.tags.outputs.branch_tag }}
          docker push ghcr.io/${{ github.repository }}:${{ steps.tags.outputs.sha_tag }}